name:                chap08
version:             0.1.0.0
github:              "https://github.com/alkazarix/book-of-monad/chap08"
license:             MIT
author:              "alkazarix"
maintainer:          "https://github.com/alkazarix"
copyright:           "2020 alkazarix"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/chap08#readme>

dependencies:
- base >= 4.7 && < 5
- stm

library:
  source-dirs: src

executables:
  chap08-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chap08

tests:
  chap08-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chap08
